/**
 * Mock food data used across the app.
 * Replace these with real API calls from lib/api.js when backend is ready.
 */

export const mockFoodItems = [
  {
    id: "1",
    name: "Fresh Organic Vegetables",
    quantity: "5 kg",
    distance: 0.8,
    expiryTime: 45,
    location: "Downtown Market",
    foodType: "Vegetables",
    provider: "Fresh Market Co.",
    providerPhone: "+91 98765 43210",
    providerEmail: "contact@freshmarket.com",
    pickupTime: "Today 2:00 PM - 6:00 PM",
    description: "A mix of fresh organic vegetables including carrots, spinach, tomatoes, and bell peppers. All locally sourced and naturally grown.",
  },
  {
    id: "2",
    name: "Freshly Baked Bread",
    quantity: "12 loaves",
    distance: 1.2,
    expiryTime: 120,
    location: "Local Bakery",
    foodType: "Bakery",
    provider: "Sweet Breads Bakery",
    providerPhone: "+91 98765 43211",
    providerEmail: "hello@sweetbreads.com",
    pickupTime: "Today 3:00 PM - 7:00 PM",
    description: "Assorted freshly baked bread loaves including wheat, sourdough, and multigrain varieties. Baked fresh this morning.",
  },
  {
    id: "3",
    name: "Mixed Fruits",
    quantity: "3 kg",
    distance: 2.1,
    expiryTime: 180,
    location: "Fruit Stand",
    foodType: "Fruits",
    provider: "Organic Fruit Hub",
    providerPhone: "+91 98765 43212",
    providerEmail: "info@organicfruit.com",
    pickupTime: "Today 1:00 PM - 5:00 PM",
    description: "Seasonal mixed fruits including apples, bananas, oranges, and grapes. Perfect for families and community kitchens.",
  },
  {
    id: "4",
    name: "Cooked Rice Dishes",
    quantity: "8 portions",
    distance: 0.5,
    expiryTime: 90,
    location: "Indian Restaurant",
    foodType: "Prepared Food",
    provider: "Spice Kitchen Restaurant",
    providerPhone: "+91 98765 43213",
    providerEmail: "reservations@spicekitchen.com",
    pickupTime: "Today 2:30 PM - 5:30 PM",
    description: "Freshly prepared rice dishes including biryani, fried rice, and dal rice. Fully cooked and ready to eat.",
  },
  {
    id: "5",
    name: "Dairy Products Bundle",
    quantity: "2 boxes",
    distance: 1.8,
    expiryTime: 240,
    location: "Grocery Store",
    foodType: "Dairy",
    provider: "Daily Grocery Mart",
    providerPhone: "+91 98765 43214",
    providerEmail: "support@dailygrocer.com",
    pickupTime: "Today 1:00 PM - 8:00 PM",
    description: "Bundle of dairy products including milk, paneer, curd, and buttermilk. All properly stored and fresh.",
  },
  {
    id: "6",
    name: "Grilled Chicken",
    quantity: "4 servings",
    distance: 3.2,
    expiryTime: 60,
    location: "BBQ Restaurant",
    foodType: "Prepared Food",
    provider: "Smoky BBQ Grill",
    providerPhone: "+91 98765 43215",
    providerEmail: "orders@smokybbq.com",
    pickupTime: "Today 2:00 PM - 5:00 PM",
    description: "Grilled chicken servings, marinated and fully cooked. Available in tandoori and classic barbecue styles.",
  },
  {
    id: "7",
    name: "Seasonal Vegetables",
    quantity: "6 kg",
    distance: 2.5,
    expiryTime: 300,
    location: "Farmer's Market",
    foodType: "Vegetables",
    provider: "Local Farmer's Market",
    providerPhone: "+91 98765 43216",
    providerEmail: "farmers@localmarket.com",
    pickupTime: "Today 12:00 PM - 6:00 PM",
    description: "Fresh seasonal vegetables straight from local farms. Includes potatoes, onions, cauliflower, and more.",
  },
  {
    id: "8",
    name: "Pasta Salad",
    quantity: "10 servings",
    distance: 1.1,
    expiryTime: 150,
    location: "Italian Deli",
    foodType: "Prepared Food",
    provider: "Bella Italia Deli",
    providerPhone: "+91 98765 43217",
    providerEmail: "hello@bellaitalia.com",
    pickupTime: "Today 3:00 PM - 6:00 PM",
    description: "Delicious pasta salad with penne, cherry tomatoes, olives, mozzarella, and homemade Italian dressing.",
  },
];
